# Generated by Django 4.2 on 2023-05-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_by', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phno', models.CharField(max_length=12)),
                ('department', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_slot', models.CharField(max_length=100)),
            ],
        ),
    ]
