# Generated by Django 4.2 on 2023-05-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium_management_app', '0002_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
